#@pathUrl = http://localhost:8080/apiv3
@pathUrl = https://apiv3.area54sa.com.ar:8125/apiv3
           
#@credenciales = Basic A54APIDev A54API4470Dev!
#@credenciales = Basic A54APIProd A54API4470Prod!
@credenciales = Basic A54APIProdUniversal A54API4470ProdUniversal!


### Activa o desactiva una empresa
PUT {{pathUrl}}/empresa/activar/133/true
Authorization: {{credenciales}}

### Activa o desactiva la autogestion de una empresa
PUT {{pathUrl}}/empresa/activarAutogestion/133/false
Authorization: {{credenciales}}

### Activa o desactiva el forzado de mostrar TyC de una empresa
PUT {{pathUrl}}/empresa/activarMostrarTyC/133/true
Authorization: {{credenciales}}

### Actualiza las opciones de autogestion de una empresa
PUT {{pathUrl}}/empresa/registrarAutogestionOpciones/133/aaa,bbb,ccc
Authorization: {{credenciales}}











### Obtiene el almacenaje previo de una empresa
GET {{pathUrl}}/empresas/getAlmacenajePeriodo/57/1900-01-01/2018-07-02
Authorization: {{credenciales}}




### Obtiene la configuración de una empresa
GET {{pathUrl}}/empresa/configuracion/10
Authorization: {{credenciales}}

### Modifica la configuración de una empresa
PATCH  {{pathUrl}}/empresas/editOneConfiguracion/10
Authorization: {{credenciales}}
Content-Type: application/json

{
    "AlmacenPrepago": ""
}



### Obtiene la configuración de todas las empresas
GET {{pathUrl}}/empresas/getAllConfiguracion
Authorization: {{credenciales}}



### Modifica la configuración de una empresa
PUT {{pathUrl}}/empresa/configuracion/10
Authorization: {{credenciales}}
Content-Type: application/json

{
    "EntregaRegularHDGuia": "Bultos|191|760|true|true",
    "EntregaRegularHDSeguro": "Bultos|0.75|100|true|true",
    "EntregaRegularHDPickingCD": "Bultos|0.75|100|true|true",
    "EntregaRegularHDComplemento": "Bultos|0.75|100|true|true"
}