@pathUrl = http://localhost:8080/apiv3
#@pathUrl = https://apiv3.area54sa.com.ar:8125/apiv3

#@credenciales = Basic A54APIDev A54API4470Dev!
#@credenciales = Basic A54APIProd A54API4470Prod!
@credenciales = Basic A54APIProdUniversal A54API4470ProdUniversal!

### Obtener una localidad por Id
GET {{pathUrl}}/localidades/getById/10646
Authorization: {{credenciales}}

### Obtener una localidad por CodigoPostal
GET {{pathUrl}}/localidades/getByCodigoPostal/1416
Authorization: {{credenciales}}
